server:
  # NAS access points
  nas_networks:
    - 192.168.1.0/24
    - 10.0.0.0/24
    - 127.0.0.1
  # RADIUS shared secret
  secret: "IoT@radius.com"
  # Authentication ports
  auth_port: 1812
  # Accounting ports
  acct_port: 1813
  # admin port for web interface
  admin_port: 8880

redis:
  host: "192.168.1.30"
  port: 6379
  db: 0
  password: "thisredispass"

kafka:
  brokers:
    - "localhost:9092"
  topic: "radiusaccounting"

logging:
  # Log file path
  file: "/var/log/gradius/radius.log"
  # Log level (debug, info, warn, error)
  level: "info"
  # Max size in MB before rotation
  max_size: 1024
  # Number of backups to keep
  max_backups: 5
